### ISSUE TITLE
Routing not working.

### ISSUE THREAD

**Issue by nsksaisaravana** [maliksahil/SPFxAngularCLI#1]
I added the Angular material dependent below module and routing starts not working. Please check.

import {BrowserAnimationsModule} from '@angular/platform-browser/animations';

**Comment by maliksahil** [comment]
Routing needs some additional considerations. You'd have to implement a custom location provider - no way for a webpart (or any composable UI) to work otherwise. This code sample is a starter, certainly more guidance/samples are needed for specific scenarios.
