### ISSUE TITLE
Update to Angular 6

### ISSUE THREAD

**Issue by damogallagher** [maliksahil/SPFxAngularCLI#13]
Hi

This is a great template.
I tried updating it to use Angular 6 with no success. Is this something that you can provide for us?

Thanks
Damien

**Comment by lgadola** [comment]
I tried this, too, but to no avail. Any plans on maintaining this very interesting template?

**Comment by maliksahil** [comment]
@damogallagher @lgadola I am reworking this template (sorry with fulltime jobs it's hard to devote time here). But I have simplified this template significantly and should make versioning on both SPFx side and Angular side a lot easier. Stay tuned, it's coming soon!
