### ISSUE TITLE
Apply Routing Lazy loading fail

### ISSUE THREAD

**Issue by trinhthang219** [maliksahil/SPFxAngularCLI#15]
Hi maliksahil,

It's a awesome project and save my time a lot, I continue with your source code and try to make it can lazy load with routing but I have a problem when it's running on sharepoint online, 
![image](https://user-images.githubusercontent.com/17841709/44778826-2a758380-aba8-11e8-9ce2-5de36e162f0d.png)

Could you help me a little bit. 

Many Thanks,
Thang Trinh

**Comment by maliksahil** [comment]
You need to implement a custom routing strategy, the URL based routing strategy is incompatible with SharePoint.
