### ISSUE TITLE
wsaupload forbidden

### ISSUE THREAD

**Issue by johnfabian** [maliksahil/SPFxAngularCLI#2]
I get the following error when running on production server workbench but works fine locally. Is this an issue with the workbench version? I don't have issue with other frameworks. 

I'm using sharepoint on-premise btw, does this work with on-premise as well or is this just for sharepoint online?

***ERROR MESSAGE:
***Failed to load component "a884f6f5-e74c-4932-972f-0e1431147413" (AppWebPart).
Original error: ***Manifest not found for component id "7263c7d0-1d6a-45ec-8d85-d4d1d234171b" and version "1.4.1".

***CALLSTACK:
Error: ***Failed to load component "a884f6f5-e74c-4932-972f-0e1431147413" (AppWebPart).
Original error: ***Manifest not found for component id "7263c7d0-1d6a-45ec-8d85-d4d1d234171b" and version "1.4.1".
    at /_layouts/15/next/spfx/sp-webpart-workbench-assembly_en-us.js?version=1:675:105711
    at <anonymous>

Console says WsaUpload.ashx  forbidden.

**Comment by maliksahil** [comment]
Are you trying this on SP on prem or Office 365?

**Comment by johnfabian** [comment]
on prem feature pack 2, i think the workbench is a different version.

**Comment by maliksahil** [comment]
Try spfx 1.1. I’ve used 1.4.2 in this sample project.

**Comment by johnfabian** [comment]
@maliksahil I'm able to take an spfx online and convert it to spfx on prem by changing the config.json and change the sp versions to 1.1.0 in package.json. works great for a default webpart but not sure what to do with angular added since I get an error 

Entry module not found: Field 'browser' doesn't contain a valid alias configuration after using description file ...points to package.json  I think this may be an angular-cli issue. Is there a configuration I can set without using entrymodule or entrymodulename ?

not sure what to do with these 2 lines 

```
"entryModule": "./src/app/app.module.ts",
"entryModuleName": "AppModule"
```


not sure how to setup the config.json or if I need to change the gulp file to override the webpack build?? 

I'm stuck changing : 
```
{
  "$schema": "https://dev.office.com/json-schemas/spfx-build/config.2.0.schema.json",
  "version": "2.0",
  "bundles": {
    "hello-world-web-part": {
      "components": [
        {
          "entrypoint": "./src/webparts/appWebPart.ts",
          "manifest": "./src/webparts/appWebPart.manifest.json",
          "entryModule": "./src/app/app.module.ts",
          "entryModuleName": "AppModule"
        }
      ]
    }
  },
  "externals": {}
}
```
TO:

```
{
  "entries": [
    {
      "entry": "./lib/webparts/appWebPart.js",
      "manifest": "./src/webparts/appWebPart.manifest.json",
      "outputPath": "./dist/appWebPart.js"
      
    }
  ],
  "externals": {}
  
}
```

I'm very close but wondering in the config.json is a show stopper since there are different schemas? Most the gov and corporations clients I've have are using On-Prem before SP Online so it's so frustrating that they can't just match them to be the same. 

Any help to get this to work with on prem would be so greatly appreciated, otherwise I think I'm going to be stuck using React with SharePoint even though I've invested so much time into angular in the last few years.

**Comment by johnfabian** [comment]
I actually got it to work, I realized I need to change entry to point to the src directory and not the lib directory so the config.json needed to be this:

```
{
  "entries": [
    {
      "entry": "./src/webparts/appWebPart.ts",
      "manifest": "./src/webparts/appWebPart.manifest.json",
      "outputPath": "./dist/appWebPart.js"
      
    }
  ],
  "externals": {}  
}

```
