### ISSUE TITLE
routing in multiuse weppart 

### ISSUE THREAD

**Issue by sezarmbar** [maliksahil/SPFxAngularCLI#3]
thank you Sahil for a great job !!!

routing work great with **one** webpart.
**But !**
1.  when i'm adding **second** webpart , only the **first router-outlet**  view routing.
2.  If i try to click the link in the **second** or **third** webpart **first router-outlet** take the event and change the rout.

how can i fix this 
thanks

**Comment by maliksahil** [comment]
For routing to work, you have to implement a custom routing strategy. Routing ootb is one of those things that does not understand two apps on the same page.

**Comment by trinhthang219** [comment]
@sezarmbar : how you can make the routing work? can you share to me your thought and source code?

**Comment by trinhthang219** [comment]
@maliksahil  Thank you for your response, Unfortunately, I just a newbie on angular, could you send me any example or give me a link that I can start learning custom routing strategy?

**Comment by maliksahil** [comment]
I don't have a sample as of now, I'll upload a new project time permitting.
