### ISSUE TITLE
Bindings Don't work

### ISSUE THREAD

**Issue by johnfabian** [maliksahil/SPFxAngularCLI#5]
I noticed in the webpart there is this line: 

```
 platformBrowserDynamic().bootstrapModuleFactory(
        AppModuleNgFactory, { ngZone: 'noop' })
      .catch(
         err => console.log(err));
```
This cause the zones not to work and I have to call ChangeDetectorRef manually which is fine but none of the 2 way bindings work.  I'm using PrimeNG controls and none of those bindings work? Is there a way to get the two way bindings to work?

Also, nothing inside of the angular-cli.json works? Whats' the point of using the CLI if none of it works besides using the command to create a couple of files ng g c ??? What's the point? 

This almost seems like it's more trouble than it's worth. Seems all good for little test projects but I'm trying to use this for real project and it's really slowing me down and it's not even that complicated of a project, I think  I could of finished by now using just typescript and no framework at all or have learned React in and completed in the amount of hrs and rabbit holes I've had to go done. Is Angular Elements going to be the same ordeal because if so I'm going to dump this for SharePoint spfx. Works great full page in a document library but I don't think this is any good for spfx. 

Is there any way to get the bindings to work with zone's turned off?

**Comment by maliksahil** [comment]
?

**Comment by johnfabian** [comment]
The two-way bindings with the zones turned off don't seem to work, I using on-premises, works great in a document library but once in a web part they don't work. If I take out { ngZone: 'noop' } then it doesn't see the  zone.js file loaded since the angular-cli file doesn't really do anything, it doesn't see the polyfills

**Comment by johnfabian** [comment]
I'll just close this, play with it some more and put a test project in my github, maybe you might see something I'm missing.
