### ISSUE TITLE
Scaffold difference in SP Online only and SP 2016

### ISSUE THREAD

**Issue by SULme** [maliksahil/SPFxAngularCLI#7]
Hello Malik,
first I'd like to thank you for providing a lot of information for SPFx in general and SPFx with Angular.
Since I'm pretty new in SharePoint development, I just have a raw idea about the difference when you scaffold a new webpart for SP Online only or for SP2016 onwards.
So my question is, is this solution for SP2016 onwards or just SP Online?
Dear regards

**Comment by maliksahil** [comment]
The project is for SP Online, although the same concept can be extrapolated to on prem. I am in the process of simplifying this project and accompanying it with a video course so it's easier to follow.
