### ISSUE TITLE
How to include styles?

### ISSUE THREAD

**Issue by Rainson12** [maliksahil/SPFxAngularCLI#8]
I want to include styles but regardless if i add them to the styles.css or app.component.css and include that one in the app.component.ts the styles wont be loaded. Any idea?

**Comment by pdcastano** [comment]
I have the same issue...

**Comment by maliksahil** [comment]
You would have to modify the gulpfile to support css. 
I am waiting for Angular 6 to release before putting more work into this. Elements will make this all a lot easier.
