### ISSUE TITLE
On-premise not working

### ISSUE THREAD

**Issue by vicko23** [maliksahil/SPFxAngularCLI#9]
It works great on DEV environment when I use 1.4.1 version of SP framework, but for on-premise I must use 1.1.0 and it does not work with that version... It would not start DEV environment neither build. In console, there is an error like: 404 manifests.js not found... Do you have any solution for this?

**Comment by maliksahil** [comment]
Yeah - this project is written for SP Online. I am in the process of simplifying this project template alongwith a video course. That should make it trivial to use it anywhere without huge baked in dependencies into what SPFx project you are using.
